# .github/workflows/integration.yml
name: Checking all functionalities
on:
  push:
    branches:
      - main
jobs:
  check:
    name: Checking all functionalities
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: "npm install"
        run: npm install
      #- name: "Updating production front-end"
      #  run: cd frontend; npm install;npm run build;cd ..
      - name: "Creating container on docker"
        run: docker run -d -p 27017:27017 mongo
      - name: Set environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GHPR }}
        run: echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      - name: "Run node server"
        run: npm start &
      - name: "Test"
        run: npm test
      
